
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class AplikasiKonversiSuhu extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiKonversiSuhu
     */
    public AplikasiKonversiSuhu() {
        initComponents();
    setLocationRelativeTo(null);

    // Item combo box
    cbDari.addItem("Celcius");
    cbDari.addItem("Fahrenheit");
    cbDari.addItem("Reamur");
    cbDari.addItem("Kelvin");

    cbKe.addItem("Celcius");
    cbKe.addItem("Fahrenheit");
    cbKe.addItem("Reamur");
    cbKe.addItem("Kelvin");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblInput = new javax.swing.JLabel();
        txtSuhu = new javax.swing.JTextField();
        lblDari = new javax.swing.JLabel();
        lblKe = new javax.swing.JLabel();
        cbDari = new javax.swing.JComboBox<>();
        cbKe = new javax.swing.JComboBox<>();
        lblHasil = new javax.swing.JLabel();
        btnKonversi = new javax.swing.JButton();
        rbOtomatis = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJudul.setText("Aplikasi Konversi Suhu");
        lblJudul.setPreferredSize(getPreferredSize());
        jPanel1.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 190, 23));

        lblInput.setText("Masukkan Value Suhu yang ingin dikonversi ke bawah");
        jPanel1.add(lblInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        txtSuhu.setText("Masukkan Value Suhu");
        txtSuhu.setPreferredSize(getPreferredSize());
        txtSuhu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSuhuFocusGained(evt);
            }
        });
        txtSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSuhuKeyTyped(evt);
            }
        });
        jPanel1.add(txtSuhu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, 30));

        lblDari.setText("Dari");
        jPanel1.add(lblDari, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        lblKe.setText("Ke");
        jPanel1.add(lblKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jPanel1.add(cbDari, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jPanel1.add(cbKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        lblHasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblHasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 225, 200, 50));

        btnKonversi.setText("Konversi");
        btnKonversi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonversiActionPerformed(evt);
            }
        });
        jPanel1.add(btnKonversi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        rbOtomatis.setText("ModeOtomatis");
        rbOtomatis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbOtomatisItemStateChanged(evt);
            }
        });
        jPanel1.add(rbOtomatis, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonversiActionPerformed
    try {
        double suhu = Double.parseDouble(txtSuhu.getText());
        String dari = cbDari.getSelectedItem().toString();
        String ke = cbKe.getSelectedItem().toString();
        double hasil = 0;

        // Konversi ke Celcius dulu sebagai acuan
        double celcius = 0;
        switch (dari) {
            case "Celcius": celcius = suhu; break;
            case "Fahrenheit": celcius = (suhu - 32) * 5 / 9; break;
            case "Reamur": celcius = suhu * 5 / 4; break;
            case "Kelvin": celcius = suhu - 273.15; break;
        }

        // Dari Celcius ke target skala
        switch (ke) {
            case "Celcius": hasil = celcius; break;
            case "Fahrenheit": hasil = (celcius * 9 / 5) + 32; break;
            case "Reamur": hasil = celcius * 4 / 5; break;
            case "Kelvin": hasil = celcius + 273.15; break;
        }

        lblHasil.setText(String.format("Hasil: %.2f %s", hasil, ke));
        JOptionPane.showMessageDialog(this, "Hasil konversi: " + hasil + " " + ke, "Konversi Sukses", JOptionPane.INFORMATION_MESSAGE);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Input harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnKonversiActionPerformed

    private void txtSuhuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuhuKeyTyped
    char c = evt.getKeyChar();
    if (Character.isISOControl(c)) {
        return;
    }


    if (!Character.isDigit(c) && c != '-') {
        evt.consume();
        JOptionPane.showMessageDialog(this, "Masukkan hanya angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_txtSuhuKeyTyped

    private void rbOtomatisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbOtomatisItemStateChanged
    if (rbOtomatis.isSelected()) {
        txtSuhu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                if (!txtSuhu.getText().isEmpty()) {
                    btnKonversi.doClick(); // jalankan otomatis tombol konversi
                }
            }
        });
    }
    }//GEN-LAST:event_rbOtomatisItemStateChanged

    private void txtSuhuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSuhuFocusGained
    txtSuhu.setText("");
    lblHasil.setText("");
    }//GEN-LAST:event_txtSuhuFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKonversiSuhu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKonversiSuhu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKonversi;
    private javax.swing.JComboBox<String> cbDari;
    private javax.swing.JComboBox<String> cbKe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDari;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblInput;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblKe;
    private javax.swing.JRadioButton rbOtomatis;
    private javax.swing.JTextField txtSuhu;
    // End of variables declaration//GEN-END:variables
}
